# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
